### PR TITLE
Allow building with mvn

### LINKED ISSUE #3: Introduce a proper build tool
I noticed this project does not use a build tool yet, so I thought you'd want to introduce one. This will allow to setup ci as well :-)

### PR DESCRIPTION
**Pull request by unicolet**
Fixes #3

### CODE REVIEW

**Review by joente — COMMENTED** [review]
Thanks @unicolet, I wonder if we should also change the package name (and `groupId`) to `technology.transceptor` because companies should use their reversed Internet domain name and maybe include `qpack` or `java-qpack` since we might create more packages in the future which are not related to qpack. So for example `technology.transceptor.qpack`?

**Comment by unicolet** [comment]
@joente applied the `package` and `groupId` name change :-) As for the artifact id, it's really up to you :-) Looks like others use the domain as a prefix, then just get creative withe artifact id, i.e.: https://search.maven.org/search?q=g:org.elasticsearch

**Comment by joente** [comment]
I think we should also add `qpack` to the package name, like package org.elasticsearch.spark and package org.elasticsearch.hadoop etc. So we get `technology.transceptor.qpack` as package name and keep `technology.transceptor` as `groupId` for maven. We have another small open source Java project [jleri](https://github.com/transceptor-technology/jleri) and this can then be renamed to `technology.transceptor.jleri`. I can also setup maven for the Java SiriDB connector and rename this package name to `technology.transceptor.siridb.connector`. For maven the `groupId` can be `technology.transceptor` for all these projects, right?

**Comment by unicolet** [comment]
> I think we should also add qpack to the package name

@joente aye captain :-) pushing changes in a sec

> For maven the groupId can be technology.transceptor for all these projects, right

yes, that seems to be the general consensus :-)

**Comment by unicolet** [comment]
@joente let me knwo if you need a hand for `jleri` :wink:

**Review by joente — APPROVED** [review]
Thx for the pr and your help @unicolet

**Comment by joente** [comment]
@unicolet, on my virtualbox I need to upgrade the `maven-surefire-plugin` to version `2.21.0` or `2.22.0`, otherwise I get a NullPointer exception. Did you have any reason for using the older `2.20.1` version?

**Comment by unicolet** [comment]
@joente not really, it was the version pulled in mvn when it generated the project from its archetype. Odd, works for me, can you share the full log?

**Comment by joente** [comment]
I think it has to do with Java 10, see: https://github.com/junit-team/junit4/issues/1513  

> looks like surefire plugin 2.20.1 is not compatible with java 10 yet, works fine with jdk 9.
Closing.

Using a newer version of the `maven-surefire-plugin` seems to solve the issue, so I will change this to `2.22.0`

**Pull request merged**
